### DISCUSSION TITLE
0.1

### DISCUSSION THREAD

**Discussion by ffenix113** [ffenix113/zigbee_home#25] [Announcements]
Initial early release.

This is for people to try the configurations and build firmware to see if it works. Ideal result is flashed device will be able to join Zigbee network and be identified.

Note: Currently it uses channel 11 for Zigbee, and it is not configurable through configuration yet. Yes, I know, this is stupid.
Multichannel support will be added in version `0.1.1`.

Generally the idea is to try new board support by providing it in your configuration:
```yaml
board:
  # Bootloader options may be:
  # arduino
  # nrf52_legacy
  # adafruit_nrf52_v132
  # adafruit_nrf52_v140_v6
  # adafruit_nrf52_v140_v7
  #
  # For boards with Adafruit bootloaders it is *required* to specify proper bootloader.
  bootloader: adafruit_nrf52_v132
```

**Note**: please be aware that Adafruit bootloader support is experimental, so please know what you are doing and how to re-flash bootloader if needed(i.e. with `openocd`, `pyocd`, `jlink` or others).

Documentation will follow this release to show more configuration options.

Please see projects README or https://ffenix113.github.io/zigbee_home/ for more information.

<hr /><em>This discussion was created from the release <a href='https://github.com/ffenix113/zigbee_home/releases/tag/0.1'>0.1</a>.</em>
