### DISCUSSION TITLE
0.1.1

### DISCUSSION THREAD

**Discussion by ffenix113** [ffenix113/zigbee_home#27] [Announcements]
Add Zigbee multichannel support.

By default device will now use all available channels, but this can be changed with config option:
```yaml
general:
  # Use only this specific channels
  zigbee_channels: [11,12,13,14,15]
```

<hr /><em>This discussion was created from the release <a href='https://github.com/ffenix113/zigbee_home/releases/tag/0.1.1'>0.1.1</a>.</em>
