### DISCUSSION TITLE
0.2

### DISCUSSION THREAD

**Discussion by ffenix113** [ffenix113/zigbee_home#30] [Announcements]
### Adafruit bootloader support

This release hopefully adds good-enough support for Adafruit bootloaders, and boards that run it. **The boards also must be supported by Zephyr.** 
The [release page](https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases) of Adafruit bootloader provides a neat list of boards that support it, and as such, they also support this project and generated firmware.

Simple firmware that would show that the firmware works(and can be connected to Zigbee network) on Adafruit bootloader:
```yaml
general:
  runevery: 1m
  board: xiao_ble # Or other supported board
board:
  bootloader: adafruit_nrf52_sd140_v7 # This value should be specific to board's bootloader.
  debug: # Debug is only needed to show that firmware has started.
    enabled: true
    console: usb
    leds:
      enabled: true
      power: led0
  leds:
    - id: led0 # Provide pins here as well if board does not have `led0`.
```

<hr /><em>This discussion was created from the release <a href='https://github.com/ffenix113/zigbee_home/releases/tag/0.2'>0.2</a>.</em>
